---
abstract: 'Decode UAV video streams in real-time'
author:
  - 'Timm Murray <tmurray@wumpus-cave.net>'
build_requires:
  ExtUtils::CBuilder: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150005'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: UAV-Pilot-Video-Ffmpeg
provides:
  UAV::Pilot::Video::Ffmpeg:
    file: lib/UAV/Pilot/Video/Ffmpeg.pm
    version: '0.3'
  UAV::Pilot::Video::H264Decoder:
    file: lib/UAV/Pilot/Video/H264Decoder.pm
  UAV::Pilot::Video::JPEGDecoder:
    file: lib/UAV/Pilot/Video/JPEGDecoder.pm
requires:
  Moose: '0'
  Test::More: '0'
  UAV::Pilot: '1.3'
  XSLoader: '0'
  namespace::autoclean: '0'
  perl: v5.14.0
resources:
  license: http://opensource.org/licenses/BSD-3-Clause
  repository: https://github.com/frezik/UAV-Pilot-Video-Ffmpeg
version: '0.3'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
